import cold.models.autogenerated as cold
import cold.utils.helpers as helpers
from pydantic import ValidationError
import json

# Define the Bill of Materials
graphite = cold.Graphite()
lco = cold.LithiumCobaltOxide()

# Build electrodes
ne = cold.Electrode(hasActiveMaterial = graphite)
pe = cold.Electrode(hasActiveMaterial = lco)

# Define electrolyte
electrolyte = cold.PolymerElectrolyte()
electrolyte.hasChargeCarrier = cold.Lithium()

# Define case
case = cold.PouchCase()

# Build cell
cell = cold.BatteryCell()
cell.hasCase = case
cell.hasPositiveElectrode = pe
cell.hasNegativeElectrode = ne
cell.hasElectrolyte = electrolyte

# Serialize to JSON-LD
json_ld = cell.to_jsonld()
print(json.dumps(json_ld, indent=4))

