import os
from cold.models.generator import generate_pydantic_classes


def test_generate_pydantic_classes(tmpdir):
    # Use a temporary directory for testing
    output_dir = tmpdir.mkdir("autogenerated")
    template_path = "src/cold/models/templates/pydantic_template.jinja2"
    classes = [{"prefLabel": ["TestClass"]}]  # Mock class input

    generate_pydantic_classes(classes, template_path, str(output_dir))
    files = os.listdir(str(output_dir))
    assert any(f.startswith("TestClass") for f in files), "Failed to generate TestClass"
