from cold.ontology.loader import load_ontology
from cold.ontology.extractor import extract_classes
from cold.models.generator import generate_pydantic_classes
import os

def test_regenerate_models(tmpdir):
    ontology = load_ontology()
    classes = extract_classes(ontology, max_classes=5)
    output_dir = tmpdir.mkdir("autogenerated")
    template_path = "src/cold/models/templates/pydantic_template.jinja2"

    generate_pydantic_classes(classes, template_path, str(output_dir))
    files = os.listdir(str(output_dir))
    assert len(files) > 0, "No models generated"
    assert "__init__.py" in files, "Lazy loader not generated"
