


from pydantic import BaseModel, Field, validator
from typing import Optional, List, Union


from ..autogenerated.RealDataModule import RealData






class NumericalPart(RealData):
    
    
    class_name: Optional[str] = Field(
        "RealData",
        alias="@type",
        
    )
    
    hasNumberValue: Optional[Union[int, float]] = Field(
        None,
        alias="hasNumberValue",
        
    )
    

    
    

    

    