import sys
import os

from cold.models import autogenerated as cold
from pydantic import ValidationError
import json

try:

    my_case = cold.CoinCase()
    my_case.hasProperty = [
        cold.Diameter(0.02, "Metre"),
        cold.Thickness(0.0032, "Metre")
    ]   
    # Serialize to JSON-LD
    json_ld = my_case.to_jsonld()
    print(json.dumps(json_ld, indent=4))

    cell = cold.ElectrochemicalDevice(hasCase=my_case)
    cell.hasProperty = cold.Diameter(0.02, "Metre")
    cell.hasPositiveElectrode = cold.PositiveElectrode()

    # Print the validated model
    print("Validated ElectrochemicalDevice:")
    print(cell)

    # Serialize to JSON-LD
    json_ld = cell.to_jsonld()
    print(json.dumps(json_ld, indent=4))

except ValidationError as e:
    print("ValidationError:")
    print(e.json())
