import sys
import os

# Add the src/ directory to sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
print(sys.path)

import cold.models.autogenerated as cold
import cold.utils.helpers as helpers
from pydantic import ValidationError
import json

try:
    ec = cold.EthyleneCarbonate()
    ec.hasProperty = cold.MassFraction(0.3, "UnitOne")
    emc = cold.EthylMethylCarbonate()
    emc.hasProperty = cold.MassFraction(0.7, "UnitOne")
    lipf6 = cold.LithiumHexafluorophosphate()
    lipf6.hasProperty = cold.MassFraction(0.127, "UnitOne")

    solvent = cold.Solvent(hasConstituent=[ec, emc])

    print(solvent)

    # Create a new dedicated class
    lp57 = cold.Solution(hasSolvent = solvent, hasSolute=lipf6)
    
    # Serialize to JSON-LD
    json_ld = lp57.to_jsonld()
    print(json.dumps(json_ld, indent=4))


except ValidationError as e:
    print("ValidationError:")
    print(e.json())
