import sys
import os

# Add the src/ directory to sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))
print(sys.path)

import cold.models.autogenerated as cold
from pydantic import ValidationError
import json

try:

    my_case = cold.R2032()
    my_case.hasProperty = cold.Diameter(20, "Kilogram")

    print(my_case.hasProperty.hasMeasurementUnit)

    
    cell = cold.ElectrochemicalDevice(hasCase=my_case)
    cell.hasProperty = cold.Diameter(10.0, "Metre")
    

    # Print the validated model
    print("Validated ElectrochemicalDevice:")
    print(cell)

    # Serialize to JSON-LD
    json_ld = cell.to_jsonld()
    print(json.dumps(json_ld, indent=4))

except ValidationError as e:
    print("ValidationError:")
    print(e.json())
