import sys
import os

# Add the src/ directory to sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
print(sys.path)

import cold.models.autogenerated as cold
import cold.utils.helpers as helpers
from pydantic import ValidationError
import json

try:

    # Create a new dedicated class
    my_lithium_foil = helpers.merge_models(cold.Lithium, cold.Foil)()
    my_lithium_foil.hasProperty = [
        cold.Thickness(1, "MilliMetre"), 
        cold.Diameter(1, "CentiMetre"),
        cold.Mass(10, "MilliGram")
    ]

    # Serialize to JSON-LD
    json_ld = my_lithium_foil.to_jsonld()
    print(json.dumps(json_ld, indent=4))


except ValidationError as e:
    print("ValidationError:")
    print(e.json())
