
import sys
import os

# Add the src/ directory to sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))
print(sys.path)

from cold.ontology.loader import load_ontology
from cold.ontology.extractor import extract_classes
from cold.models.generator import generate_pydantic_classes

ONTOLOGY_URL = "https://w3id.org/emmo/domain/battery/inferred"
OUTPUT_DIR = "src/cold/models/autogenerated/"
TEMPLATE_PATH = "src/cold/models/templates/pydantic_template.jinja2"


def main():
    ontology = load_ontology(ONTOLOGY_URL)
    classes = extract_classes(ontology)
    generate_pydantic_classes(classes, TEMPLATE_PATH, OUTPUT_DIR)


if __name__ == "__main__":
    main()
