import cold.models.autogenerated as cold
import cold.utils.helpers as helpers
from pydantic import ValidationError
import json

print(cold.Object.mro())
print(cold.Mixture.mro())
print(cold.StateOfMatter.mro())
print(cold.ContinuumSubstance.mro())
print(cold.Substance.mro())
print(cold.GasMixture.mro())
print(cold.Suspension.mro())
print(cold.Gas.mro())