import cold.models.autogenerated as cold
import cold.utils.helpers as helpers
from pydantic import ValidationError
import json


# Create a new dedicated class
my_lithium_foil = helpers.merge_models(cold.Lithium, cold.Foil)()
my_lithium_foil.hasProperty = [
    cold.Thickness(1, "MilliMetre"), 
    cold.Diameter(1, "CentiMetre"),
    cold.Mass(10, "MilliGram")
]

# Serialize to JSON-LD
json_ld = my_lithium_foil.to_jsonld()
print(json.dumps(json_ld, indent=4))

