import sys
import os

# Add the directory to sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
print(sys.path)

import cold.models.autogenerated as cold
import cold.utils.helpers as helpers
from pydantic import ValidationError
import json


# Instantiate data model
my_cr2032 = cold.CR2032()

# Assign properties
my_cr2032.hasProperty = [cold.NominalVoltage(3.2, "Volt")]

# Serialize to JSON-LD
json_ld = my_cr2032.to_jsonld()
print(json.dumps(json_ld, indent=4))

