import cold.models.autogenerated as cold
import cold.utils.helpers as helpers
from pydantic import ValidationError
import json




# Create a new dedicated class
product = cold.ManufacturedProduct()
product.creator = "Simon"




print(product)

# Serialize to JSON-LD
json_ld = product.to_jsonld()
print(json.dumps(json_ld, indent=4))

