name: docs

on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'  # Runs on all PRs for validation

env:
  GIT_USER_NAME: "GitHub Actions"
  GIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"

jobs:

  build-docs:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository (Force Clean)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies from pyproject.toml
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]

    - name: Install System Dependencies
      run: sudo apt-get update -y && sudo apt-get install -y pandoc

    - name: Build Documentation
      run: |
        sphinx-build -b html docs/ docs/_build/html/

    - name: Upload Artifacts (for PR Validation)
      uses: actions/upload-artifact@v4
      with:
        name: "Documentation_Build"
        path: docs/_build/html/

  deploy-docs:
    
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      contents: write
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies from pyproject.toml
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]

    - name: Install System Dependencies
      run: sudo apt-get update -y && sudo apt-get install -y pandoc

    - name: Build Documentation
      run: |
        sphinx-build -b html docs/ docs/_build/html/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
