


from pydantic import BaseModel, Field, validator
from typing import Optional, List, Union


from ..autogenerated.RealModule import Real






class NumericalPart(Real):
    
    
    class_name: Optional[str] = Field(
        "Real",
        alias="@type",
        
    )
    
    hasNumericalValue: Optional[Union[int, float]] = Field(
        None,
        alias="hasNumericalValue",
        
    )
    

    
    

    

    